### ISSUE TITLE
Inclination source override from text files

### ISSUE THREAD

**Issue by karinsandstrom** [akleroy/galbase#11]
It appears that when the override text file is used to replace the LEDA inclination (and presumably other parameters, although I haven't documented this) the "LEDA" source tag is not actually replaced with "NONE".

**Comment by akleroy** [comment]
OK - so I see the issue now.

The override files add the reference via REF_INCL or similar. I.e., you override the reference field at the same time you override the value field.

So we need to hack the override_orient file or similar to add a "HERACLES" or whatever reference for those things. It's not the code, but the override files.

**Comment by akleroy** [comment]
Dealt with and closed.
